#!/bin/sh
# 2011-10-07 18:33:07
# Move files to a directory like /home/trash which you don't need them
# and you can also recover them.

files=
trash=/home/trash
log=$trash/.log

#move
move()
{
    if [ -e $files ]
    then
        mv $files $trash
        echo -e "`date +%F\ %T` :: $files `pwd`" >>$log
    fi
}

#recover
recover()
{
    if [ -e $trash/$files ]
    then
        fpath=$(awk -v fparg="$files" '$4 ~ fparg { print $5 }' $log)
        mv $trash/$files $fpath
        fpline="$files $fpath"
        cat $log | grep -v "$fpline" >$trash/.log-tmp
        mv $trash/{.log-tmp,.log} -f   #update log file
    fi
}

#run
rf=$1
ra=$@
rn=$#
run()
{
    case $rf in
        -r) farg=($ra)
            let i=1
            while [ $i -lt $rn ]
            do
                files=${farg[$i]}
                recover
                let i++
            done
            ;;
        -c) echo "Cleanning ......"
            tlimit
            echo "Done"
            ;;
        -m) marg=($ra)
           let j=0
           while [ $j -lt $rn ]
           do
               files=${marg[$j]}
               move
               let j++
           done
           ;;
    esac
}

#remove and  update log file
rulog()
{
    rm $trash/$files -f
    grep -v "$tline" $log > $trash/.log-rtmp
    mv $trash/{.log-rtmp,.log} -f
    let i--
    let numl--
}

#time limit
tlimit()
{
    nyear=$(date +%Y)
    nmonth=$(date +%m)
    nday=$(date +%d)
    numl=$(wc -l $log | awk '{ print $1 }')
    let i=1
    while [ $i -le $numl ]
    do
        tline=$(head -$i $log | tail -1)
        files=$(echo $tline | awk '{ print $4 }')
        tyear=$(echo $tline | awk '{ print $1 }' | sed 's/-.*$//')
        tmonth=$(echo $tline | awk '{ print $1 }' | sed 's/-/ /g' | awk '{ print $2 }')
        tday=$(echo $tline | awk '{ print $1 }' | sed 's/^.*-//')
        let i++
        if [ $tyear -lt $nyear ]
        then
            rulog
        fi
        if [ $tday -lt $nday ]
        then
            let "trm = $nmonth - 3"
            if [ $tmonth -le $trm ]
            then
                rulog
            fi
        else
            let "fom = $nmonth - 4"
            if [ $tmonth -le $fom ]
            then
                rulog
            fi
        fi
    done
}
        
#files
if [ $# -eq 0 ]
then
    echo "No input.Have fun!"
else
    run
fi
