#!/bin/sh
# 2011-10-07 18:33:07
# Move files to a directory like /home/trash which you don't need them
# and you can also recover them.

files=
trash=/home/trash
log=$trash/.log

#move
move()
{
    if [ -e $files ]
    then
        nfiles=$(echo $files | sed 's/\/$//' | sed 's/^.*\///g')
        anfiles=$nfiles
        nchar=$(echo $files | cut -c1)
        if [ "$nchar" != "/" ]
        then
            comp=$(echo $files | grep -v "/")  #relative path to remove
            if [ -z $comp ]
            then
                cpath=$(echo $files | awk -F "$nfiles" '{ print $1 }')
                cd $cpath
                files=`pwd`/$nfiles
            fi
        fi
        if [ -e $trash/$nfiles ]   #same name in $trash
        then
            let i=1
            while [ 1 -eq 1 ]
            do
                if [ -e $trash/$nfiles-$i ]
                then
                    let i++
                else
                    mv $files $trash/$nfiles-$i 
                    anfiles=$nfiles-$i  #trash file name write to $log
                    break
                fi
            done
        else
            mv $files $trash
        fi
        nchar=$(echo $files | cut -c1)
        if [ "$nchar" != "/" ]
        then
            echo -e "`date +%F\ %T` :: $nfiles `pwd`" >>$log
        else
            npath=$(echo $files | awk -F "$nfiles" '{ print $1 }' | sed 's/\/$//')
            echo -e "`date +%F\ %T` :: $anfiles $npath" >>$log
        fi
    else
        echo "$files: No such file or directory"
    fi
}

#recover
recover()
{
    if [ -e $trash/$files ]
    then
        fpath=$(awk -v fparg="$files" '$4 ~ fparg { print $5 }' $log)
        mv $trash/$files $fpath
        fpline="$files $fpath"
        cat $log | grep -v "$fpline" >$trash/.log-tmp
        mv $trash/{.log-tmp,.log} -f   #update log file
    else
        echo "$files: No such file or directory in $trash"
    fi
}

#remove and  update log file
rulog()
{
    [ -e $trash/$files ] && rm $trash/$files -rf
    grep -v "$files $tpath" $log > $trash/.log-rtmp
    mv $trash/{.log-rtmp,.log} -f
    let i=0
}

#time limit
tlimit()
{
    nyear=$(date +%Y)
    nmonth=$(date +%m)
    nday=$(date +%d)
    while read tdate ttime tsegm files tpath  #read from $log
    do
        let i=1
        tyear=$(echo $tdate | sed 's/-.*$//')
        tmonth=$(echo $tdate | sed 's/-/ /g' | awk '{ print $2 }')
        tday=$(echo $tdate | sed 's/^.*-//')
        [ $tyear -lt $nyear ] && rulog
        if [ $tday -lt $nday ]
        then
            let "trm = $nmonth - 3"
            [ $tmonth -le $trm ] && rulog
        else
            let "fom = $nmonth - 4"
            [ $tmonth -le $fom ] && rulog
        fi
        [ $i -eq 1 ] && break   #no file remove break
    done <$log
}
        
#run
#$1,$@,$# in function is empty
rf=$1
ra=$@
rn=$#
run()
{
    case $rf in
        -r) farg=($ra)
            let i=1
            while [ $i -lt $rn ]
            do
                files=${farg[$i]}
                recover
                let i++
            done
            ;;
        -c) echo "Cleanning ......"
            tlimit
            echo "Done"
            ;;
        *) marg=($ra)
           let j=0
           while [ $j -lt $rn ]
           do
               files=${marg[$j]}
               move
               let j++
           done
           ;;
    esac
}

#files
if [ $# -eq 0 ]
then
    echo "No input.Have fun!"
else
    run
fi
