#!/bin/sh
# 2011-12-12 13:11:25
# Copyright 2011 Yu Tsao
# Update FreeDNS IP

# Usage
get_Usage()
{
    echo "Copyright 2011 Yu Tsao."
    echo "Usage: uip -h ,--help ,get help"
    echo "       uip -u HOST URL ,update host by url which get from FreeDNS XML"
    echo "       uip -f FILE ,update by a file contain hosts and urls"
}

# Error
get_Error()
{
    echo "Error: option error, try --help"
}

# Get current IP
get_currentIP()
{
    exec 6<>/dev/tcp/whatismyipaddress.com/80
    echo -e "GET / HTTP/1.0\n" >&6
    currentIP=$(cat <&6 | grep "Your IP" | awk '{ print $5 }' | sed 's/<.*$//')
}

#Use host to get old IP
get_oldIP()
{
    oldIP=$(host $1 | head -1 | cut -f 4 -d " ")   
}

# Check IP if need to update
checkIP()
{
    if [ "$currentIP" == "$oldIP" ] ; then
        i=0
        echo "IP not changed."
    else
        echo "IP has changed and will be updated."
    fi
}

# Update IP,You should go to http://freedns.afraid.org/api/ to check the XML.
updateIP()
{
    if [ $# -lt 1 ] || [ $# -gt 3 ] ; then
        get_Error
    elif [ $# -eq 1 ] ; then
        case $1 in
            -h|--help) get_Usage
                       ;;
            *) get_Error ;;
        esac 
    elif [ $# -eq 2 ] ; then
        case $1 in
            -f) if [ -e $2 ] ; then
                    get_currentIP
                    for line in $(cat $2) ; do
                        host=$(echo $line | cut -f 1 -d ",")  #use cut and awk
                        urls=$(echo $line | awk -F "," '{ print $2 }')
                        echo -e "$host -> \c"
                        get_oldIP $host
                        checkIP
                        if [ $i -eq 0 ] ; then
                            continue
                        fi
                        curl -s http://freedns.afraid.org/dynamic/update.php?$urls
                    done
                else
                    echo "Error: file $2 not found"
                fi
                ;;
            *) get_Error ;;
        esac
    elif [ $# -eq 3 ] ; then
        case $1 in
            -u) get_oldIP $2
                get_currentIP
                checkIP
                if [ $i -eq 0 ] ; then
                    exit 0
                fi
                curl -s http://freedns.afraid.org/dynamic/update.php?$3
                ;;
           *) get_Error ;;
        esac
    fi
}
    
# Check the IP and update.
updateIP $@
