#!/bin/sh
# 2011-09-06 18:58:33
# Start applications and also arguments

tmp=
let i=0

for arg in $(echo $@) ; do
    type $arg >/dev/null 2>&1
    if [ $? -eq 0 ] ; then  #if $? is zero,arg is command
        if [ $i -eq 0 ] ; then
            tmp=
        fi
        $tmp >/dev/null 2>&1 &  #run command previous
        tmp=$arg
        let i=1
    else
        $tmp $arg >/dev/null 2>&1 &
        let i=0
    fi
done

#if the last arg is command
if [ $i -eq 1 ] ; then
    $tmp >/dev/null 2>&1 &
fi
